services:
  - type: web
    name: vk-spotting-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python vk_bot.py
    envVars:
      - key: PORT
        value: 10000
